#include "Map.h"

MapTile::MapTile(std::string name)
{
    m_name = name;
}

bool MapTile::isAdjacentToTile(MapTile* tile)
{
    for (auto e : tile->getAdjacentTiles()) {
        if (e == this) {
            return true;
        }
    }
    return false;
}

void MapTile::addAdjacentTile(MapTile* tile)
{
    m_adjacentTiles.insert(tile); //Add the tile to this tile's list of adjacent tiles
    if (!tile->isAdjacentToTile(this))
    {
        tile->addAdjacentTile(this); //Reciprocally connect
    }
}

std::set<MapTile*> MapTile::getAdjacentTiles()
{
    return m_adjacentTiles;
}

std::string MapTile::getName()
{
    return m_name;
}

//Map

void Map::addTile(MapTile* tile)
{
    m_tilesByName.insert(std::pair<std::string, MapTile*>(tile->getName(), tile));
}

MapTile* Map::getTileByName(std::string name)
{
    return m_tilesByName.find(name)->second;
}

/*/std::set<MapTile*> Map::getReachableTilesFromTile(MapTile* tile, int distance)
{
    //Todo, this is SUPER inefficient, but I was struggling to make
    //an efficient version work. It can be made to run much faster though,
    //because right now it needlessly re-checks tiles that it's already checked every loop.
    std::set<MapTile*> output;
    output.insert(tile);
    for (int i = 0; i < distance; i++) {
        std::set<MapTile*> layer;
        for (auto tile : output) {
            for (auto child : tile->getAdjacentTiles()) {
                layer.insert(child);
            }
        }
        for (auto tile: layer) {
            output.insert(tile);
        }
    }
    
    return output;
}/*/

std::set<MapTile*> Map::getReachableTilesFromTile(MapTile* tile, int distance)
{
    //May be able to be made more efficient, not sure.
    std::set<MapTile*> output;
    std::set<MapTile*> lastLayer;
    output.insert(tile);
    lastLayer.insert(tile);
    
    for (int i = 0; i < distance; i++) {
        std::set<MapTile*> currentLayer;
        for (auto tile : lastLayer) {
            for (auto child : tile->getAdjacentTiles()) {
                //Only insert this newfound tile to the current layer if it hasn't been seen before.
                std::set<MapTile*>::iterator it = output.find(child);
                if (it == output.end()) {
                    currentLayer.insert(child);
                }
            }
        }
        for (auto tile: currentLayer) {
            output.insert(tile);
        }
        lastLayer = currentLayer;
    }
    
    return output;
}

std::set<MapTile*> Map::getReachableTilesFromTile(std::string tileName, int distance)
{
    MapTile* tile = getTileByName(tileName);
    return getReachableTilesFromTile(tile, distance);
}

//

Map::Map()
{
    MapTile a1("a1");
    addTile(&a1);
    MapTile a2("a2");
    addTile(&a2);
    MapTile a3("a3");
    addTile(&a3);
    MapTile a4("a4");
    addTile(&a4);
    MapTile a5("a5");
    addTile(&a5);
    MapTile a6("a6");
    addTile(&a6);
    MapTile a7("a7");
    addTile(&a7);
    MapTile a8("a8");
    addTile(&a8);
    MapTile a9("a9");
    addTile(&a9);
    MapTile a10("a10");
    addTile(&a10);
    MapTile a11("a11");
    addTile(&a11);
    MapTile a12("a12");
    addTile(&a12);
    MapTile a13("a13");
    addTile(&a13);
    MapTile a14("a14");
    addTile(&a14);
    MapTile a15("a15");
    addTile(&a15);
    MapTile a16("a16");
    addTile(&a16);
    MapTile b1("b1");
    addTile(&b1);
    MapTile b2("b2");
    addTile(&b2);
    MapTile b3("b3");
    addTile(&b3);
    MapTile b4("b4");
    addTile(&b4);
    MapTile b5("b5");
    addTile(&b5);
    MapTile b6("b6");
    addTile(&b6);
    MapTile b7("b7");
    addTile(&b7);
    MapTile b8("b8");
    addTile(&b8);
    MapTile b9("b9");
    addTile(&b9);
    MapTile b10("b10");
    addTile(&b10);
    MapTile b11("b11");
    addTile(&b11);
    MapTile b12("b12");
    addTile(&b12);
    MapTile b13("b13");
    addTile(&b13);
    MapTile b14("b14");
    addTile(&b14);
    MapTile b15("b15");
    addTile(&b15);
    MapTile b16("b16");
    addTile(&b16);
    MapTile c1("c1");
    addTile(&c1);
    MapTile c2("c2");
    addTile(&c2);
    MapTile c3("c3");
    addTile(&c3);
    MapTile c4("c4");
    addTile(&c4);
    MapTile c5("c5");
    addTile(&c5);
    MapTile c6("c6");
    addTile(&c6);
    MapTile c7("c7");
    addTile(&c7);
    MapTile c8("c8");
    addTile(&c8);
    MapTile c9("c9");
    addTile(&c9);
    MapTile c10("c10");
    addTile(&c10);
    MapTile c11("c11");
    addTile(&c11);
    MapTile c12("c12");
    addTile(&c12);
    MapTile c13("c13");
    addTile(&c13);
    MapTile c14("c14");
    addTile(&c14);
    MapTile c15("c15");
    addTile(&c15);
    MapTile c16("c16");
    addTile(&c16);
    MapTile d1("d1");
    addTile(&d1);
    MapTile d2("d2");
    addTile(&d2);
    MapTile d3("d3");
    addTile(&d3);
    MapTile d4("d4");
    addTile(&d4);
    MapTile d5("d5");
    addTile(&d5);
    MapTile d6("d6");
    addTile(&d6);
    MapTile d7("d7");
    addTile(&d7);
    MapTile d8("d8");
    addTile(&d8);
    MapTile d9("d9");
    addTile(&d9);
    MapTile d10("d10");
    addTile(&d10);
    MapTile d11("d11");
    addTile(&d11);
    MapTile d12("d12");
    addTile(&d12);
    MapTile d13("d13");
    addTile(&d13);
    MapTile d14("d14");
    addTile(&d14);
    MapTile d15("d15");
    addTile(&d15);
    MapTile d16("d16");
    addTile(&d16);
    MapTile e1("e1");
    addTile(&e1);
    MapTile e2("e2");
    addTile(&e2);
    MapTile e3("e3");
    addTile(&e3);
    MapTile e4("e4");
    addTile(&e4);
    MapTile e5("e5");
    addTile(&e5);
    MapTile e6("e6");
    addTile(&e6);
    MapTile e7("e7");
    addTile(&e7);
    MapTile e8("e8");
    addTile(&e8);
    MapTile e9("e9");
    addTile(&e9);
    MapTile e10("e10");
    addTile(&e10);
    MapTile e11("e11");
    addTile(&e11);
    MapTile e12("e12");
    addTile(&e12);
    MapTile e13("e13");
    addTile(&e13);
    MapTile e14("e14");
    addTile(&e14);
    MapTile e15("e15");
    addTile(&e15);
    MapTile e16("e16");
    addTile(&e16);
    MapTile f1("f1");
    addTile(&f1);
    MapTile f2("f2");
    addTile(&f2);
    MapTile f3("f3");
    addTile(&f3);
    MapTile f4("f4");
    addTile(&f4);
    MapTile f5("f5");
    addTile(&f5);
    MapTile f6("f6");
    addTile(&f6);
    MapTile f7("f7");
    addTile(&f7);
    MapTile f8("f8");
    addTile(&f8);
    MapTile f9("f9");
    addTile(&f9);
    MapTile f10("f10");
    addTile(&f10);
    MapTile f11("f11");
    addTile(&f11);
    MapTile f12("f12");
    addTile(&f12);
    MapTile f13("f13");
    addTile(&f13);
    MapTile f14("f14");
    addTile(&f14);
    MapTile f15("f15");
    addTile(&f15);
    MapTile f16("f16");
    addTile(&f16);
    MapTile g1("g1");
    addTile(&g1);
    MapTile g2("g2");
    addTile(&g2);
    MapTile g3("g3");
    addTile(&g3);
    MapTile g4("g4");
    addTile(&g4);
    MapTile g5("g5");
    addTile(&g5);
    MapTile g6("g6");
    addTile(&g6);
    MapTile g7("g7");
    addTile(&g7);
    MapTile g8("g8");
    addTile(&g8);
    MapTile g9("g9");
    addTile(&g9);
    MapTile g10("g10");
    addTile(&g10);
    MapTile g11("g11");
    addTile(&g11);
    MapTile g12("g12");
    addTile(&g12);
    MapTile g13("g13");
    addTile(&g13);
    MapTile g14("g14");
    addTile(&g14);
    MapTile g15("g15");
    addTile(&g15);
    MapTile g16("g16");
    addTile(&g16);
    MapTile h1("h1");
    addTile(&h1);
    MapTile h2("h2");
    addTile(&h2);
    MapTile h3("h3");
    addTile(&h3);
    MapTile h4("h4");
    addTile(&h4);
    MapTile h5("h5");
    addTile(&h5);
    MapTile h6("h6");
    addTile(&h6);
    MapTile h7("h7");
    addTile(&h7);
    MapTile h8("h8");
    addTile(&h8);
    MapTile h9("h9");
    addTile(&h9);
    MapTile h10("h10");
    addTile(&h10);
    MapTile h11("h11");
    addTile(&h11);
    MapTile h12("h12");
    addTile(&h12);
    MapTile h13("h13");
    addTile(&h13);
    MapTile h14("h14");
    addTile(&h14);
    MapTile h15("h15");
    addTile(&h15);
    MapTile h16("h16");
    addTile(&h16);
    MapTile i1("i1");
    addTile(&i1);
    MapTile i2("i2");
    addTile(&i2);
    MapTile i3("i3");
    addTile(&i3);
    MapTile i4("i4");
    addTile(&i4);
    MapTile i5("i5");
    addTile(&i5);
    MapTile i6("i6");
    addTile(&i6);
    MapTile i7("i7");
    addTile(&i7);
    MapTile i8("i8");
    addTile(&i8);
    MapTile i9("i9");
    addTile(&i9);
    MapTile i10("i10");
    addTile(&i10);
    MapTile i11("i11");
    addTile(&i11);
    MapTile i12("i12");
    addTile(&i12);
    MapTile i13("i13");
    addTile(&i13);
    MapTile i14("i14");
    addTile(&i14);
    MapTile i15("i15");
    addTile(&i15);
    MapTile i16("i16");
    addTile(&i16);
    MapTile j1("j1");
    addTile(&j1);
    MapTile j2("j2");
    addTile(&j2);
    MapTile j3("j3");
    addTile(&j3);
    MapTile j4("j4");
    addTile(&j4);
    MapTile j5("j5");
    addTile(&j5);
    MapTile j6("j6");
    addTile(&j6);
    MapTile j7("j7");
    addTile(&j7);
    MapTile j8("j8");
    addTile(&j8);
    MapTile j9("j9");
    addTile(&j9);
    MapTile j10("j10");
    addTile(&j10);
    MapTile j11("j11");
    addTile(&j11);
    MapTile j12("j12");
    addTile(&j12);
    MapTile j13("j13");
    addTile(&j13);
    MapTile j14("j14");
    addTile(&j14);
    MapTile j15("j15");
    addTile(&j15);
    MapTile j16("j16");
    addTile(&j16);
    MapTile k1("k1");
    addTile(&k1);
    MapTile k2("k2");
    addTile(&k2);
    MapTile k3("k3");
    addTile(&k3);
    MapTile k4("k4");
    addTile(&k4);
    MapTile k5("k5");
    addTile(&k5);
    MapTile k6("k6");
    addTile(&k6);
    MapTile k7("k7");
    addTile(&k7);
    MapTile k8("k8");
    addTile(&k8);
    MapTile k9("k9");
    addTile(&k9);
    MapTile k10("k10");
    addTile(&k10);
    MapTile k11("k11");
    addTile(&k11);
    MapTile k12("k12");
    addTile(&k12);
    MapTile k13("k13");
    addTile(&k13);
    MapTile k14("k14");
    addTile(&k14);
    MapTile k15("k15");
    addTile(&k15);
    MapTile k16("k16");
    addTile(&k16);
    MapTile l1("l1");
    addTile(&l1);
    MapTile l2("l2");
    addTile(&l2);
    MapTile l3("l3");
    addTile(&l3);
    MapTile l4("l4");
    addTile(&l4);
    MapTile l5("l5");
    addTile(&l5);
    MapTile l6("l6");
    addTile(&l6);
    MapTile l7("l7");
    addTile(&l7);
    MapTile l8("l8");
    addTile(&l8);
    MapTile l9("l9");
    addTile(&l9);
    MapTile l10("l10");
    addTile(&l10);
    MapTile l11("l11");
    addTile(&l11);
    MapTile l12("l12");
    addTile(&l12);
    MapTile l13("l13");
    addTile(&l13);
    MapTile l14("l14");
    addTile(&l14);
    MapTile l15("l15");
    addTile(&l15);
    MapTile l16("l16");
    addTile(&l16);
    MapTile m1("m1");
    addTile(&m1);
    MapTile m2("m2");
    addTile(&m2);
    MapTile m3("m3");
    addTile(&m3);
    MapTile m4("m4");
    addTile(&m4);
    MapTile m5("m5");
    addTile(&m5);
    MapTile m6("m6");
    addTile(&m6);
    MapTile m7("m7");
    addTile(&m7);
    MapTile m8("m8");
    addTile(&m8);
    MapTile m9("m9");
    addTile(&m9);
    MapTile m10("m10");
    addTile(&m10);
    MapTile m11("m11");
    addTile(&m11);
    MapTile m12("m12");
    addTile(&m12);
    MapTile m13("m13");
    addTile(&m13);
    MapTile m14("m14");
    addTile(&m14);
    MapTile m15("m15");
    addTile(&m15);
    MapTile m16("m16");
    addTile(&m16);
    MapTile n1("n1");
    addTile(&n1);
    MapTile n2("n2");
    addTile(&n2);
    MapTile n3("n3");
    addTile(&n3);
    MapTile n4("n4");
    addTile(&n4);
    MapTile n5("n5");
    addTile(&n5);
    MapTile n6("n6");
    addTile(&n6);
    MapTile n7("n7");
    addTile(&n7);
    MapTile n8("n8");
    addTile(&n8);
    MapTile n9("n9");
    addTile(&n9);
    MapTile n10("n10");
    addTile(&n10);
    MapTile n11("n11");
    addTile(&n11);
    MapTile n12("n12");
    addTile(&n12);
    MapTile n13("n13");
    addTile(&n13);
    MapTile n14("n14");
    addTile(&n14);
    MapTile n15("n15");
    addTile(&n15);
    MapTile n16("n16");
    addTile(&n16);
    MapTile o1("o1");
    addTile(&o1);
    MapTile o2("o2");
    addTile(&o2);
    MapTile o3("o3");
    addTile(&o3);
    MapTile o4("o4");
    addTile(&o4);
    MapTile o5("o5");
    addTile(&o5);
    MapTile o6("o6");
    addTile(&o6);
    MapTile o7("o7");
    addTile(&o7);
    MapTile o8("o8");
    addTile(&o8);
    MapTile o9("o9");
    addTile(&o9);
    MapTile o10("o10");
    addTile(&o10);
    MapTile o11("o11");
    addTile(&o11);
    MapTile o12("o12");
    addTile(&o12);
    MapTile o13("o13");
    addTile(&o13);
    MapTile o14("o14");
    addTile(&o14);
    MapTile o15("o15");
    addTile(&o15);
    MapTile o16("o16");
    addTile(&o16);
    MapTile p1("p1");
    addTile(&p1);
    MapTile p2("p2");
    addTile(&p2);
    MapTile p3("p3");
    addTile(&p3);
    MapTile p4("p4");
    addTile(&p4);
    MapTile p5("p5");
    addTile(&p5);
    MapTile p6("p6");
    addTile(&p6);
    MapTile p7("p7");
    addTile(&p7);
    MapTile p8("p8");
    addTile(&p8);
    MapTile p9("p9");
    addTile(&p9);
    MapTile p10("p10");
    addTile(&p10);
    MapTile p11("p11");
    addTile(&p11);
    MapTile p12("p12");
    addTile(&p12);
    MapTile p13("p13");
    addTile(&p13);
    MapTile p14("p14");
    addTile(&p14);
    MapTile p15("p15");
    addTile(&p15);
    MapTile p16("p16");
    addTile(&p16);
    a1.addAdjacentTile(&a2);
    a1.addAdjacentTile(&b2);
    a1.addAdjacentTile(&b1);
    a2.addAdjacentTile(&a3);
    a2.addAdjacentTile(&b1);
    a2.addAdjacentTile(&a1);
    a2.addAdjacentTile(&b2);
    a2.addAdjacentTile(&b3);
    a3.addAdjacentTile(&b4);
    a3.addAdjacentTile(&a2);
    a3.addAdjacentTile(&b2);
    a3.addAdjacentTile(&a4);
    a3.addAdjacentTile(&b3);
    a4.addAdjacentTile(&b4);
    a4.addAdjacentTile(&a3);
    a4.addAdjacentTile(&b5);
    a4.addAdjacentTile(&a5);
    a4.addAdjacentTile(&b3);
    a5.addAdjacentTile(&b4);
    a5.addAdjacentTile(&a6);
    a5.addAdjacentTile(&b5);
    a5.addAdjacentTile(&b6);
    a5.addAdjacentTile(&a4);
    a6.addAdjacentTile(&b5);
    a6.addAdjacentTile(&a5);
    a6.addAdjacentTile(&b6);
    a6.addAdjacentTile(&a7);
    a6.addAdjacentTile(&b7);
    a7.addAdjacentTile(&a6);
    a7.addAdjacentTile(&b6);
    a7.addAdjacentTile(&b7);
    a7.addAdjacentTile(&a8);
    a7.addAdjacentTile(&b8);
    a8.addAdjacentTile(&a9);
    a8.addAdjacentTile(&b9);
    a8.addAdjacentTile(&a7);
    a8.addAdjacentTile(&b7);
    a8.addAdjacentTile(&b8);
    a9.addAdjacentTile(&b9);
    a9.addAdjacentTile(&a8);
    a9.addAdjacentTile(&b8);
    a10.addAdjacentTile(&a11);
    a10.addAdjacentTile(&b11);
    a10.addAdjacentTile(&b10);
    a11.addAdjacentTile(&a10);
    a11.addAdjacentTile(&b10);
    a11.addAdjacentTile(&b11);
    a11.addAdjacentTile(&b12);
    a11.addAdjacentTile(&a12);
    a12.addAdjacentTile(&b13);
    a12.addAdjacentTile(&a13);
    a12.addAdjacentTile(&a11);
    a12.addAdjacentTile(&b11);
    a12.addAdjacentTile(&b12);
    a13.addAdjacentTile(&b13);
    a13.addAdjacentTile(&b14);
    a13.addAdjacentTile(&a14);
    a13.addAdjacentTile(&b12);
    a13.addAdjacentTile(&a12);
    a14.addAdjacentTile(&b13);
    a14.addAdjacentTile(&a13);
    a14.addAdjacentTile(&b14);
    a14.addAdjacentTile(&b15);
    a14.addAdjacentTile(&a15);
    a15.addAdjacentTile(&a16);
    a15.addAdjacentTile(&b14);
    a15.addAdjacentTile(&a14);
    a15.addAdjacentTile(&b15);
    a15.addAdjacentTile(&b16);
    a16.addAdjacentTile(&b16);
    a16.addAdjacentTile(&b15);
    a16.addAdjacentTile(&a15);
    b1.addAdjacentTile(&c1);
    b1.addAdjacentTile(&c2);
    b1.addAdjacentTile(&a1);
    b1.addAdjacentTile(&b2);
    b1.addAdjacentTile(&a2);
    b2.addAdjacentTile(&c1);
    b2.addAdjacentTile(&b3);
    b2.addAdjacentTile(&c2);
    b2.addAdjacentTile(&a3);
    b2.addAdjacentTile(&b1);
    b2.addAdjacentTile(&c3);
    b2.addAdjacentTile(&a1);
    b2.addAdjacentTile(&a2);
    b3.addAdjacentTile(&b4);
    b3.addAdjacentTile(&c2);
    b3.addAdjacentTile(&a3);
    b3.addAdjacentTile(&c3);
    b3.addAdjacentTile(&b2);
    b3.addAdjacentTile(&c4);
    b3.addAdjacentTile(&a4);
    b3.addAdjacentTile(&a2);
    b4.addAdjacentTile(&a3);
    b4.addAdjacentTile(&b5);
    b4.addAdjacentTile(&a5);
    b4.addAdjacentTile(&c3);
    b4.addAdjacentTile(&c4);
    b4.addAdjacentTile(&a4);
    b4.addAdjacentTile(&b3);
    b5.addAdjacentTile(&b4);
    b5.addAdjacentTile(&a6);
    b5.addAdjacentTile(&a5);
    b5.addAdjacentTile(&b6);
    b5.addAdjacentTile(&c4);
    b5.addAdjacentTile(&a4);
    b6.addAdjacentTile(&a6);
    b6.addAdjacentTile(&b5);
    b6.addAdjacentTile(&a5);
    b6.addAdjacentTile(&a7);
    b6.addAdjacentTile(&b7);
    b7.addAdjacentTile(&a6);
    b7.addAdjacentTile(&b6);
    b7.addAdjacentTile(&a7);
    b7.addAdjacentTile(&a8);
    b7.addAdjacentTile(&b8);
    b8.addAdjacentTile(&a9);
    b8.addAdjacentTile(&b9);
    b8.addAdjacentTile(&a7);
    b8.addAdjacentTile(&b7);
    b8.addAdjacentTile(&c9);
    b8.addAdjacentTile(&a8);
    b9.addAdjacentTile(&a9);
    b9.addAdjacentTile(&c8);
    b9.addAdjacentTile(&c9);
    b9.addAdjacentTile(&a8);
    b9.addAdjacentTile(&b8);
    b10.addAdjacentTile(&a11);
    b10.addAdjacentTile(&a10);
    b10.addAdjacentTile(&b11);
    b11.addAdjacentTile(&a10);
    b11.addAdjacentTile(&b10);
    b11.addAdjacentTile(&a11);
    b11.addAdjacentTile(&b12);
    b11.addAdjacentTile(&a12);
    b12.addAdjacentTile(&b13);
    b12.addAdjacentTile(&a13);
    b12.addAdjacentTile(&a11);
    b12.addAdjacentTile(&c13);
    b12.addAdjacentTile(&b11);
    b12.addAdjacentTile(&a12);
    b13.addAdjacentTile(&a13);
    b13.addAdjacentTile(&b14);
    b13.addAdjacentTile(&a14);
    b13.addAdjacentTile(&c13);
    b13.addAdjacentTile(&c14);
    b13.addAdjacentTile(&b12);
    b13.addAdjacentTile(&a12);
    b14.addAdjacentTile(&c15);
    b14.addAdjacentTile(&b13);
    b14.addAdjacentTile(&a13);
    b14.addAdjacentTile(&a14);
    b14.addAdjacentTile(&b15);
    b14.addAdjacentTile(&c13);
    b14.addAdjacentTile(&a15);
    b14.addAdjacentTile(&c14);
    b15.addAdjacentTile(&c15);
    b15.addAdjacentTile(&a16);
    b15.addAdjacentTile(&c16);
    b15.addAdjacentTile(&b14);
    b15.addAdjacentTile(&a14);
    b15.addAdjacentTile(&a15);
    b15.addAdjacentTile(&b16);
    b15.addAdjacentTile(&c14);
    b16.addAdjacentTile(&c15);
    b16.addAdjacentTile(&a16);
    b16.addAdjacentTile(&c16);
    b16.addAdjacentTile(&b15);
    b16.addAdjacentTile(&a15);
    c1.addAdjacentTile(&c2);
    c1.addAdjacentTile(&b1);
    c1.addAdjacentTile(&d1);
    c1.addAdjacentTile(&b2);
    c1.addAdjacentTile(&d2);
    c2.addAdjacentTile(&c1);
    c2.addAdjacentTile(&b1);
    c2.addAdjacentTile(&c3);
    c2.addAdjacentTile(&d1);
    c2.addAdjacentTile(&b2);
    c2.addAdjacentTile(&d2);
    c2.addAdjacentTile(&b3);
    c2.addAdjacentTile(&d3);
    c3.addAdjacentTile(&b4);
    c3.addAdjacentTile(&d4);
    c3.addAdjacentTile(&c2);
    c3.addAdjacentTile(&b2);
    c3.addAdjacentTile(&c4);
    c3.addAdjacentTile(&d2);
    c3.addAdjacentTile(&b3);
    c3.addAdjacentTile(&d3);
    c4.addAdjacentTile(&b4);
    c4.addAdjacentTile(&d4);
    c4.addAdjacentTile(&b5);
    c4.addAdjacentTile(&c3);
    c4.addAdjacentTile(&b3);
    c4.addAdjacentTile(&d3);
    c5.addAdjacentTile(&c6);
    c5.addAdjacentTile(&d5);
    c5.addAdjacentTile(&d6);
    c6.addAdjacentTile(&c7);
    c6.addAdjacentTile(&d5);
    c6.addAdjacentTile(&d6);
    c6.addAdjacentTile(&d7);
    c6.addAdjacentTile(&c5);
    c7.addAdjacentTile(&d7);
    c7.addAdjacentTile(&c6);
    c7.addAdjacentTile(&d6);
    c8.addAdjacentTile(&b9);
    c8.addAdjacentTile(&d8);
    c8.addAdjacentTile(&d9);
    c8.addAdjacentTile(&c9);
    c9.addAdjacentTile(&d8);
    c9.addAdjacentTile(&b9);
    c9.addAdjacentTile(&d9);
    c9.addAdjacentTile(&c8);
    c9.addAdjacentTile(&b8);
    c10.addAdjacentTile(&d11);
    c10.addAdjacentTile(&c11);
    c10.addAdjacentTile(&d10);
    c11.addAdjacentTile(&c12);
    c11.addAdjacentTile(&d10);
    c11.addAdjacentTile(&d11);
    c11.addAdjacentTile(&d12);
    c11.addAdjacentTile(&c10);
    c12.addAdjacentTile(&d13);
    c12.addAdjacentTile(&d12);
    c12.addAdjacentTile(&c11);
    c12.addAdjacentTile(&d11);
    c13.addAdjacentTile(&d12);
    c13.addAdjacentTile(&b13);
    c13.addAdjacentTile(&d13);
    c13.addAdjacentTile(&b14);
    c13.addAdjacentTile(&d14);
    c13.addAdjacentTile(&c14);
    c13.addAdjacentTile(&b12);
    c14.addAdjacentTile(&c15);
    c14.addAdjacentTile(&b13);
    c14.addAdjacentTile(&d13);
    c14.addAdjacentTile(&b14);
    c14.addAdjacentTile(&d14);
    c14.addAdjacentTile(&b15);
    c14.addAdjacentTile(&c13);
    c14.addAdjacentTile(&d15);
    c15.addAdjacentTile(&c16);
    c15.addAdjacentTile(&b14);
    c15.addAdjacentTile(&d14);
    c15.addAdjacentTile(&b15);
    c15.addAdjacentTile(&d15);
    c15.addAdjacentTile(&b16);
    c15.addAdjacentTile(&c14);
    c15.addAdjacentTile(&d16);
    c16.addAdjacentTile(&c15);
    c16.addAdjacentTile(&b15);
    c16.addAdjacentTile(&d15);
    c16.addAdjacentTile(&b16);
    c16.addAdjacentTile(&d16);
    d1.addAdjacentTile(&c1);
    d1.addAdjacentTile(&e1);
    d1.addAdjacentTile(&c2);
    d1.addAdjacentTile(&e2);
    d1.addAdjacentTile(&d2);
    d2.addAdjacentTile(&c1);
    d2.addAdjacentTile(&e1);
    d2.addAdjacentTile(&c2);
    d2.addAdjacentTile(&e2);
    d2.addAdjacentTile(&c3);
    d2.addAdjacentTile(&d1);
    d2.addAdjacentTile(&d3);
    d3.addAdjacentTile(&d4);
    d3.addAdjacentTile(&c2);
    d3.addAdjacentTile(&e2);
    d3.addAdjacentTile(&c3);
    d3.addAdjacentTile(&c4);
    d3.addAdjacentTile(&d2);
    d4.addAdjacentTile(&d3);
    d4.addAdjacentTile(&c4);
    d4.addAdjacentTile(&c3);
    d5.addAdjacentTile(&c6);
    d5.addAdjacentTile(&c5);
    d5.addAdjacentTile(&d6);
    d5.addAdjacentTile(&e6);
    d6.addAdjacentTile(&e5);
    d6.addAdjacentTile(&c6);
    d6.addAdjacentTile(&e6);
    d6.addAdjacentTile(&c7);
    d6.addAdjacentTile(&d5);
    d6.addAdjacentTile(&e7);
    d6.addAdjacentTile(&d7);
    d6.addAdjacentTile(&c5);
    d7.addAdjacentTile(&c6);
    d7.addAdjacentTile(&e6);
    d7.addAdjacentTile(&c7);
    d7.addAdjacentTile(&e7);
    d7.addAdjacentTile(&d6);
    d7.addAdjacentTile(&e8);
    d8.addAdjacentTile(&d9);
    d8.addAdjacentTile(&e7);
    d8.addAdjacentTile(&c8);
    d8.addAdjacentTile(&e8);
    d8.addAdjacentTile(&c9);
    d8.addAdjacentTile(&e9);
    d9.addAdjacentTile(&d8);
    d9.addAdjacentTile(&e10);
    d9.addAdjacentTile(&c8);
    d9.addAdjacentTile(&e8);
    d9.addAdjacentTile(&c9);
    d9.addAdjacentTile(&e9);
    d10.addAdjacentTile(&e10);
    d10.addAdjacentTile(&c11);
    d10.addAdjacentTile(&e11);
    d10.addAdjacentTile(&d11);
    d10.addAdjacentTile(&e9);
    d10.addAdjacentTile(&c10);
    d11.addAdjacentTile(&e10);
    d11.addAdjacentTile(&c11);
    d11.addAdjacentTile(&e11);
    d11.addAdjacentTile(&c12);
    d11.addAdjacentTile(&d10);
    d11.addAdjacentTile(&e12);
    d11.addAdjacentTile(&d12);
    d11.addAdjacentTile(&c10);
    d12.addAdjacentTile(&c11);
    d12.addAdjacentTile(&d13);
    d12.addAdjacentTile(&e11);
    d12.addAdjacentTile(&c12);
    d12.addAdjacentTile(&c13);
    d12.addAdjacentTile(&d11);
    d13.addAdjacentTile(&c12);
    d13.addAdjacentTile(&d14);
    d13.addAdjacentTile(&c13);
    d13.addAdjacentTile(&c14);
    d13.addAdjacentTile(&d12);
    d14.addAdjacentTile(&c15);
    d14.addAdjacentTile(&d13);
    d14.addAdjacentTile(&c13);
    d14.addAdjacentTile(&d15);
    d14.addAdjacentTile(&c14);
    d15.addAdjacentTile(&c15);
    d15.addAdjacentTile(&c16);
    d15.addAdjacentTile(&e16);
    d15.addAdjacentTile(&d14);
    d15.addAdjacentTile(&c14);
    d15.addAdjacentTile(&d16);
    d16.addAdjacentTile(&c15);
    d16.addAdjacentTile(&e15);
    d16.addAdjacentTile(&c16);
    d16.addAdjacentTile(&e16);
    d16.addAdjacentTile(&d15);
    e1.addAdjacentTile(&e2);
    e1.addAdjacentTile(&d1);
    e1.addAdjacentTile(&f1);
    e1.addAdjacentTile(&d2);
    e1.addAdjacentTile(&f2);
    e2.addAdjacentTile(&e1);
    e2.addAdjacentTile(&d1);
    e2.addAdjacentTile(&f1);
    e2.addAdjacentTile(&d2);
    e2.addAdjacentTile(&f2);
    e2.addAdjacentTile(&d3);
    e3.addAdjacentTile(&e4);
    e3.addAdjacentTile(&f3);
    e3.addAdjacentTile(&f4);
    e4.addAdjacentTile(&e5);
    e4.addAdjacentTile(&f3);
    e4.addAdjacentTile(&f4);
    e4.addAdjacentTile(&f5);
    e4.addAdjacentTile(&e3);
    e5.addAdjacentTile(&e6);
    e5.addAdjacentTile(&f4);
    e5.addAdjacentTile(&f5);
    e5.addAdjacentTile(&d6);
    e5.addAdjacentTile(&f6);
    e5.addAdjacentTile(&e4);
    e6.addAdjacentTile(&e5);
    e6.addAdjacentTile(&d5);
    e6.addAdjacentTile(&e7);
    e6.addAdjacentTile(&f5);
    e6.addAdjacentTile(&d6);
    e6.addAdjacentTile(&f6);
    e6.addAdjacentTile(&d7);
    e6.addAdjacentTile(&f7);
    e7.addAdjacentTile(&d8);
    e7.addAdjacentTile(&f8);
    e7.addAdjacentTile(&e6);
    e7.addAdjacentTile(&d6);
    e7.addAdjacentTile(&e8);
    e7.addAdjacentTile(&f6);
    e7.addAdjacentTile(&d7);
    e7.addAdjacentTile(&f7);
    e8.addAdjacentTile(&d8);
    e8.addAdjacentTile(&f8);
    e8.addAdjacentTile(&d9);
    e8.addAdjacentTile(&f9);
    e8.addAdjacentTile(&e7);
    e8.addAdjacentTile(&d7);
    e8.addAdjacentTile(&e9);
    e8.addAdjacentTile(&f7);
    e9.addAdjacentTile(&d8);
    e9.addAdjacentTile(&e10);
    e9.addAdjacentTile(&f8);
    e9.addAdjacentTile(&d9);
    e9.addAdjacentTile(&f9);
    e9.addAdjacentTile(&d10);
    e9.addAdjacentTile(&f10);
    e9.addAdjacentTile(&e8);
    e10.addAdjacentTile(&d9);
    e10.addAdjacentTile(&e11);
    e10.addAdjacentTile(&f9);
    e10.addAdjacentTile(&d10);
    e10.addAdjacentTile(&f10);
    e10.addAdjacentTile(&d11);
    e10.addAdjacentTile(&f11);
    e10.addAdjacentTile(&e9);
    e11.addAdjacentTile(&f12);
    e11.addAdjacentTile(&e10);
    e11.addAdjacentTile(&d10);
    e11.addAdjacentTile(&e12);
    e11.addAdjacentTile(&f10);
    e11.addAdjacentTile(&d11);
    e11.addAdjacentTile(&f11);
    e11.addAdjacentTile(&d12);
    e12.addAdjacentTile(&f12);
    e12.addAdjacentTile(&f13);
    e12.addAdjacentTile(&e11);
    e12.addAdjacentTile(&d11);
    e12.addAdjacentTile(&e13);
    e12.addAdjacentTile(&f11);
    e13.addAdjacentTile(&f12);
    e13.addAdjacentTile(&f13);
    e13.addAdjacentTile(&f14);
    e13.addAdjacentTile(&e12);
    e13.addAdjacentTile(&e14);
    e14.addAdjacentTile(&e13);
    e14.addAdjacentTile(&f13);
    e14.addAdjacentTile(&f14);
    e15.addAdjacentTile(&e16);
    e15.addAdjacentTile(&f16);
    e15.addAdjacentTile(&d16);
    e15.addAdjacentTile(&f15);
    e16.addAdjacentTile(&e15);
    e16.addAdjacentTile(&d16);
    e16.addAdjacentTile(&f15);
    e16.addAdjacentTile(&d15);
    e16.addAdjacentTile(&f16);
    f1.addAdjacentTile(&e1);
    f1.addAdjacentTile(&g1);
    f1.addAdjacentTile(&e2);
    f1.addAdjacentTile(&g2);
    f1.addAdjacentTile(&f2);
    f2.addAdjacentTile(&g1);
    f2.addAdjacentTile(&f1);
    f2.addAdjacentTile(&e2);
    f2.addAdjacentTile(&e1);
    f3.addAdjacentTile(&f4);
    f3.addAdjacentTile(&g2);
    f3.addAdjacentTile(&e3);
    f3.addAdjacentTile(&g3);
    f3.addAdjacentTile(&e4);
    f3.addAdjacentTile(&g4);
    f4.addAdjacentTile(&e5);
    f4.addAdjacentTile(&f3);
    f4.addAdjacentTile(&f5);
    f4.addAdjacentTile(&e3);
    f4.addAdjacentTile(&g3);
    f4.addAdjacentTile(&e4);
    f4.addAdjacentTile(&g4);
    f5.addAdjacentTile(&e5);
    f5.addAdjacentTile(&e6);
    f5.addAdjacentTile(&f4);
    f5.addAdjacentTile(&f6);
    f5.addAdjacentTile(&e4);
    f5.addAdjacentTile(&g4);
    f6.addAdjacentTile(&e5);
    f6.addAdjacentTile(&e6);
    f6.addAdjacentTile(&e7);
    f6.addAdjacentTile(&f5);
    f6.addAdjacentTile(&f7);
    f7.addAdjacentTile(&f8);
    f7.addAdjacentTile(&e6);
    f7.addAdjacentTile(&e7);
    f7.addAdjacentTile(&e8);
    f7.addAdjacentTile(&f6);
    f8.addAdjacentTile(&g9);
    f8.addAdjacentTile(&f9);
    f8.addAdjacentTile(&e7);
    f8.addAdjacentTile(&e8);
    f8.addAdjacentTile(&e9);
    f8.addAdjacentTile(&f7);
    f9.addAdjacentTile(&g9);
    f9.addAdjacentTile(&e10);
    f9.addAdjacentTile(&f8);
    f9.addAdjacentTile(&g10);
    f9.addAdjacentTile(&f10);
    f9.addAdjacentTile(&e8);
    f9.addAdjacentTile(&g8);
    f9.addAdjacentTile(&e9);
    f10.addAdjacentTile(&g9);
    f10.addAdjacentTile(&e10);
    f10.addAdjacentTile(&e11);
    f10.addAdjacentTile(&f9);
    f10.addAdjacentTile(&f11);
    f10.addAdjacentTile(&e9);
    f11.addAdjacentTile(&f12);
    f11.addAdjacentTile(&e10);
    f11.addAdjacentTile(&e11);
    f11.addAdjacentTile(&e12);
    f11.addAdjacentTile(&f10);
    f11.addAdjacentTile(&g12);
    f12.addAdjacentTile(&f13);
    f12.addAdjacentTile(&e11);
    f12.addAdjacentTile(&g11);
    f12.addAdjacentTile(&e12);
    f12.addAdjacentTile(&g12);
    f12.addAdjacentTile(&e13);
    f12.addAdjacentTile(&f11);
    f12.addAdjacentTile(&g13);
    f13.addAdjacentTile(&f12);
    f13.addAdjacentTile(&f14);
    f13.addAdjacentTile(&e12);
    f13.addAdjacentTile(&g12);
    f13.addAdjacentTile(&e13);
    f13.addAdjacentTile(&e14);
    f14.addAdjacentTile(&e13);
    f14.addAdjacentTile(&f13);
    f14.addAdjacentTile(&e14);
    f15.addAdjacentTile(&g14);
    f15.addAdjacentTile(&e15);
    f15.addAdjacentTile(&g15);
    f15.addAdjacentTile(&e16);
    f15.addAdjacentTile(&g16);
    f15.addAdjacentTile(&f16);
    f16.addAdjacentTile(&e15);
    f16.addAdjacentTile(&g15);
    f16.addAdjacentTile(&e16);
    f16.addAdjacentTile(&g16);
    f16.addAdjacentTile(&f15);
    g1.addAdjacentTile(&g2);
    g1.addAdjacentTile(&f1);
    g1.addAdjacentTile(&h1);
    g1.addAdjacentTile(&f2);
    g1.addAdjacentTile(&h2);
    g2.addAdjacentTile(&f3);
    g2.addAdjacentTile(&h3);
    g2.addAdjacentTile(&g1);
    g2.addAdjacentTile(&f1);
    g2.addAdjacentTile(&g3);
    g2.addAdjacentTile(&h1);
    g2.addAdjacentTile(&h2);
    g3.addAdjacentTile(&f3);
    g3.addAdjacentTile(&h3);
    g3.addAdjacentTile(&f4);
    g3.addAdjacentTile(&h4);
    g3.addAdjacentTile(&g2);
    g3.addAdjacentTile(&g4);
    g3.addAdjacentTile(&h2);
    g4.addAdjacentTile(&f3);
    g4.addAdjacentTile(&h3);
    g4.addAdjacentTile(&f4);
    g4.addAdjacentTile(&h4);
    g4.addAdjacentTile(&f5);
    g4.addAdjacentTile(&h5);
    g4.addAdjacentTile(&g3);
    g5.addAdjacentTile(&h6);
    g5.addAdjacentTile(&g6);
    g5.addAdjacentTile(&h5);
    g5.addAdjacentTile(&h4);
    g6.addAdjacentTile(&h7);
    g6.addAdjacentTile(&g5);
    g6.addAdjacentTile(&g7);
    g6.addAdjacentTile(&h5);
    g6.addAdjacentTile(&h6);
    g7.addAdjacentTile(&g8);
    g7.addAdjacentTile(&h7);
    g7.addAdjacentTile(&g6);
    g7.addAdjacentTile(&h6);
    g8.addAdjacentTile(&g9);
    g8.addAdjacentTile(&g7);
    g8.addAdjacentTile(&f9);
    g8.addAdjacentTile(&h7);
    g9.addAdjacentTile(&f8);
    g9.addAdjacentTile(&g10);
    g9.addAdjacentTile(&f9);
    g9.addAdjacentTile(&f10);
    g9.addAdjacentTile(&h10);
    g9.addAdjacentTile(&g8);
    g10.addAdjacentTile(&g9);
    g10.addAdjacentTile(&f9);
    g10.addAdjacentTile(&h10);
    g11.addAdjacentTile(&h12);
    g11.addAdjacentTile(&f12);
    g11.addAdjacentTile(&g12);
    g11.addAdjacentTile(&h11);
    g12.addAdjacentTile(&f12);
    g12.addAdjacentTile(&h12);
    g12.addAdjacentTile(&f13);
    g12.addAdjacentTile(&h13);
    g12.addAdjacentTile(&g11);
    g12.addAdjacentTile(&f11);
    g12.addAdjacentTile(&g13);
    g12.addAdjacentTile(&h11);
    g13.addAdjacentTile(&f12);
    g13.addAdjacentTile(&g14);
    g13.addAdjacentTile(&h12);
    g13.addAdjacentTile(&h13);
    g13.addAdjacentTile(&h14);
    g13.addAdjacentTile(&g12);
    g14.addAdjacentTile(&g15);
    g14.addAdjacentTile(&h13);
    g14.addAdjacentTile(&h14);
    g14.addAdjacentTile(&f15);
    g14.addAdjacentTile(&h15);
    g14.addAdjacentTile(&g13);
    g15.addAdjacentTile(&h16);
    g15.addAdjacentTile(&g14);
    g15.addAdjacentTile(&g16);
    g15.addAdjacentTile(&h14);
    g15.addAdjacentTile(&f15);
    g15.addAdjacentTile(&h15);
    g15.addAdjacentTile(&f16);
    g16.addAdjacentTile(&h16);
    g16.addAdjacentTile(&g15);
    g16.addAdjacentTile(&f15);
    g16.addAdjacentTile(&h15);
    g16.addAdjacentTile(&f16);
    h1.addAdjacentTile(&g1);
    h1.addAdjacentTile(&h2);
    h1.addAdjacentTile(&g2);
    h2.addAdjacentTile(&h3);
    h2.addAdjacentTile(&g1);
    h2.addAdjacentTile(&g2);
    h2.addAdjacentTile(&g3);
    h2.addAdjacentTile(&h1);
    h3.addAdjacentTile(&i4);
    h3.addAdjacentTile(&h4);
    h3.addAdjacentTile(&g2);
    h3.addAdjacentTile(&g3);
    h3.addAdjacentTile(&g4);
    h3.addAdjacentTile(&h2);
    h4.addAdjacentTile(&g5);
    h4.addAdjacentTile(&h3);
    h4.addAdjacentTile(&i5);
    h4.addAdjacentTile(&h5);
    h4.addAdjacentTile(&g3);
    h4.addAdjacentTile(&i3);
    h4.addAdjacentTile(&g4);
    h4.addAdjacentTile(&i4);
    h5.addAdjacentTile(&i4);
    h5.addAdjacentTile(&g5);
    h5.addAdjacentTile(&i5);
    h5.addAdjacentTile(&g6);
    h5.addAdjacentTile(&h4);
    h5.addAdjacentTile(&i6);
    h5.addAdjacentTile(&h6);
    h5.addAdjacentTile(&g4);
    h6.addAdjacentTile(&g5);
    h6.addAdjacentTile(&i5);
    h6.addAdjacentTile(&g6);
    h6.addAdjacentTile(&i6);
    h6.addAdjacentTile(&g7);
    h6.addAdjacentTile(&h5);
    h7.addAdjacentTile(&g8);
    h7.addAdjacentTile(&g7);
    h7.addAdjacentTile(&g6);
    h7.addAdjacentTile(&i7);
    h8.addAdjacentTile(&h9);
    h8.addAdjacentTile(&i9);
    h8.addAdjacentTile(&i8);
    h9.addAdjacentTile(&h8);
    h9.addAdjacentTile(&i9);
    h9.addAdjacentTile(&i8);
    h10.addAdjacentTile(&g9);
    h10.addAdjacentTile(&i11);
    h10.addAdjacentTile(&i10);
    h10.addAdjacentTile(&g10);
    h11.addAdjacentTile(&h12);
    h11.addAdjacentTile(&i10);
    h11.addAdjacentTile(&g11);
    h11.addAdjacentTile(&i11);
    h11.addAdjacentTile(&g12);
    h11.addAdjacentTile(&i12);
    h12.addAdjacentTile(&i13);
    h12.addAdjacentTile(&h13);
    h12.addAdjacentTile(&g11);
    h12.addAdjacentTile(&i11);
    h12.addAdjacentTile(&g12);
    h12.addAdjacentTile(&i12);
    h12.addAdjacentTile(&g13);
    h12.addAdjacentTile(&h11);
    h13.addAdjacentTile(&g14);
    h13.addAdjacentTile(&h12);
    h13.addAdjacentTile(&h14);
    h13.addAdjacentTile(&g12);
    h13.addAdjacentTile(&i12);
    h13.addAdjacentTile(&g13);
    h14.addAdjacentTile(&g14);
    h14.addAdjacentTile(&g15);
    h14.addAdjacentTile(&h13);
    h14.addAdjacentTile(&h15);
    h14.addAdjacentTile(&g13);
    h15.addAdjacentTile(&h16);
    h15.addAdjacentTile(&g14);
    h15.addAdjacentTile(&g15);
    h15.addAdjacentTile(&g16);
    h15.addAdjacentTile(&h14);
    h16.addAdjacentTile(&g16);
    h16.addAdjacentTile(&g15);
    h16.addAdjacentTile(&h15);
    i1.addAdjacentTile(&j2);
    i1.addAdjacentTile(&j1);
    i1.addAdjacentTile(&i2);
    i2.addAdjacentTile(&j2);
    i2.addAdjacentTile(&i1);
    i2.addAdjacentTile(&j3);
    i2.addAdjacentTile(&i3);
    i2.addAdjacentTile(&j1);
    i3.addAdjacentTile(&j2);
    i3.addAdjacentTile(&j3);
    i3.addAdjacentTile(&h4);
    i3.addAdjacentTile(&i2);
    i3.addAdjacentTile(&j4);
    i3.addAdjacentTile(&i4);
    i4.addAdjacentTile(&h3);
    i4.addAdjacentTile(&i5);
    i4.addAdjacentTile(&j3);
    i4.addAdjacentTile(&h4);
    i4.addAdjacentTile(&j4);
    i4.addAdjacentTile(&h5);
    i4.addAdjacentTile(&i3);
    i4.addAdjacentTile(&j5);
    i5.addAdjacentTile(&h4);
    i5.addAdjacentTile(&i6);
    i5.addAdjacentTile(&j4);
    i5.addAdjacentTile(&h5);
    i5.addAdjacentTile(&j5);
    i5.addAdjacentTile(&h6);
    i5.addAdjacentTile(&i4);
    i5.addAdjacentTile(&j6);
    i6.addAdjacentTile(&i5);
    i6.addAdjacentTile(&h5);
    i6.addAdjacentTile(&j5);
    i6.addAdjacentTile(&h6);
    i6.addAdjacentTile(&j6);
    i7.addAdjacentTile(&h7);
    i7.addAdjacentTile(&j8);
    i7.addAdjacentTile(&j7);
    i8.addAdjacentTile(&h9);
    i8.addAdjacentTile(&h8);
    i8.addAdjacentTile(&i9);
    i9.addAdjacentTile(&h9);
    i9.addAdjacentTile(&h8);
    i9.addAdjacentTile(&i8);
    i10.addAdjacentTile(&j11);
    i10.addAdjacentTile(&i11);
    i10.addAdjacentTile(&j9);
    i10.addAdjacentTile(&h10);
    i10.addAdjacentTile(&j10);
    i10.addAdjacentTile(&h11);
    i11.addAdjacentTile(&j11);
    i11.addAdjacentTile(&h12);
    i11.addAdjacentTile(&j12);
    i11.addAdjacentTile(&i10);
    i11.addAdjacentTile(&h10);
    i11.addAdjacentTile(&i12);
    i11.addAdjacentTile(&j10);
    i11.addAdjacentTile(&h11);
    i12.addAdjacentTile(&i13);
    i12.addAdjacentTile(&j11);
    i12.addAdjacentTile(&h12);
    i12.addAdjacentTile(&j12);
    i12.addAdjacentTile(&h13);
    i12.addAdjacentTile(&j13);
    i12.addAdjacentTile(&i11);
    i12.addAdjacentTile(&h11);
    i13.addAdjacentTile(&h12);
    i13.addAdjacentTile(&i14);
    i13.addAdjacentTile(&j12);
    i13.addAdjacentTile(&j13);
    i13.addAdjacentTile(&j14);
    i13.addAdjacentTile(&i12);
    i14.addAdjacentTile(&i13);
    i14.addAdjacentTile(&j15);
    i14.addAdjacentTile(&j13);
    i14.addAdjacentTile(&j14);
    i15.addAdjacentTile(&j16);
    i15.addAdjacentTile(&i16);
    i15.addAdjacentTile(&j15);
    i15.addAdjacentTile(&j14);
    i16.addAdjacentTile(&j15);
    i16.addAdjacentTile(&j16);
    i16.addAdjacentTile(&i15);
    j1.addAdjacentTile(&j2);
    j1.addAdjacentTile(&i1);
    j1.addAdjacentTile(&k1);
    j1.addAdjacentTile(&i2);
    j1.addAdjacentTile(&k2);
    j2.addAdjacentTile(&i1);
    j2.addAdjacentTile(&j3);
    j2.addAdjacentTile(&k1);
    j2.addAdjacentTile(&i2);
    j2.addAdjacentTile(&i3);
    j2.addAdjacentTile(&k3);
    j2.addAdjacentTile(&j1);
    j3.addAdjacentTile(&k4);
    j3.addAdjacentTile(&j2);
    j3.addAdjacentTile(&i2);
    j3.addAdjacentTile(&j4);
    j3.addAdjacentTile(&i3);
    j3.addAdjacentTile(&k3);
    j3.addAdjacentTile(&i4);
    j4.addAdjacentTile(&k4);
    j4.addAdjacentTile(&i5);
    j4.addAdjacentTile(&k5);
    j4.addAdjacentTile(&j3);
    j4.addAdjacentTile(&i3);
    j4.addAdjacentTile(&j5);
    j4.addAdjacentTile(&k3);
    j4.addAdjacentTile(&i4);
    j5.addAdjacentTile(&k4);
    j5.addAdjacentTile(&i5);
    j5.addAdjacentTile(&k5);
    j5.addAdjacentTile(&i6);
    j5.addAdjacentTile(&k6);
    j5.addAdjacentTile(&j4);
    j5.addAdjacentTile(&i4);
    j5.addAdjacentTile(&j6);
    j6.addAdjacentTile(&i5);
    j6.addAdjacentTile(&k5);
    j6.addAdjacentTile(&k6);
    j6.addAdjacentTile(&i6);
    j6.addAdjacentTile(&j5);
    j7.addAdjacentTile(&j8);
    j7.addAdjacentTile(&i7);
    j8.addAdjacentTile(&j7);
    j8.addAdjacentTile(&j9);
    j8.addAdjacentTile(&i7);
    j9.addAdjacentTile(&i10);
    j9.addAdjacentTile(&j10);
    j9.addAdjacentTile(&j8);
    j9.addAdjacentTile(&k10);
    j10.addAdjacentTile(&k9);
    j10.addAdjacentTile(&i10);
    j10.addAdjacentTile(&k10);
    j10.addAdjacentTile(&i11);
    j10.addAdjacentTile(&j9);
    j11.addAdjacentTile(&j12);
    j11.addAdjacentTile(&i10);
    j11.addAdjacentTile(&i11);
    j11.addAdjacentTile(&k11);
    j11.addAdjacentTile(&i12);
    j11.addAdjacentTile(&k12);
    j12.addAdjacentTile(&i13);
    j12.addAdjacentTile(&j11);
    j12.addAdjacentTile(&k13);
    j12.addAdjacentTile(&j13);
    j12.addAdjacentTile(&i11);
    j12.addAdjacentTile(&k11);
    j12.addAdjacentTile(&i12);
    j12.addAdjacentTile(&k12);
    j13.addAdjacentTile(&i13);
    j13.addAdjacentTile(&k13);
    j13.addAdjacentTile(&i14);
    j13.addAdjacentTile(&j12);
    j13.addAdjacentTile(&k14);
    j13.addAdjacentTile(&j14);
    j13.addAdjacentTile(&i12);
    j13.addAdjacentTile(&k12);
    j14.addAdjacentTile(&i13);
    j14.addAdjacentTile(&k13);
    j14.addAdjacentTile(&i14);
    j14.addAdjacentTile(&k14);
    j14.addAdjacentTile(&i15);
    j14.addAdjacentTile(&j13);
    j14.addAdjacentTile(&k15);
    j14.addAdjacentTile(&j15);
    j15.addAdjacentTile(&j16);
    j15.addAdjacentTile(&i14);
    j15.addAdjacentTile(&k14);
    j15.addAdjacentTile(&i15);
    j15.addAdjacentTile(&k15);
    j15.addAdjacentTile(&i16);
    j15.addAdjacentTile(&j14);
    j15.addAdjacentTile(&k16);
    j16.addAdjacentTile(&i15);
    j16.addAdjacentTile(&k15);
    j16.addAdjacentTile(&i16);
    j16.addAdjacentTile(&k16);
    j16.addAdjacentTile(&j15);
    k1.addAdjacentTile(&l1);
    k1.addAdjacentTile(&j2);
    k1.addAdjacentTile(&l2);
    k1.addAdjacentTile(&k2);
    k1.addAdjacentTile(&j1);
    k2.addAdjacentTile(&l1);
    k2.addAdjacentTile(&k1);
    k2.addAdjacentTile(&j1);
    k2.addAdjacentTile(&l2);
    k3.addAdjacentTile(&k4);
    k3.addAdjacentTile(&j2);
    k3.addAdjacentTile(&j3);
    k3.addAdjacentTile(&l3);
    k3.addAdjacentTile(&j4);
    k3.addAdjacentTile(&l4);
    k4.addAdjacentTile(&j3);
    k4.addAdjacentTile(&l3);
    k4.addAdjacentTile(&j4);
    k4.addAdjacentTile(&l4);
    k4.addAdjacentTile(&j5);
    k4.addAdjacentTile(&k3);
    k5.addAdjacentTile(&l6);
    k5.addAdjacentTile(&k6);
    k5.addAdjacentTile(&j4);
    k5.addAdjacentTile(&j5);
    k5.addAdjacentTile(&l5);
    k5.addAdjacentTile(&j6);
    k6.addAdjacentTile(&l6);
    k6.addAdjacentTile(&k5);
    k6.addAdjacentTile(&j5);
    k6.addAdjacentTile(&l5);
    k6.addAdjacentTile(&j6);
    k7.addAdjacentTile(&l8);
    k7.addAdjacentTile(&l7);
    k7.addAdjacentTile(&k8);
    k8.addAdjacentTile(&k9);
    k8.addAdjacentTile(&l7);
    k8.addAdjacentTile(&l8);
    k8.addAdjacentTile(&k7);
    k8.addAdjacentTile(&l9);
    k9.addAdjacentTile(&k10);
    k9.addAdjacentTile(&l8);
    k9.addAdjacentTile(&l9);
    k9.addAdjacentTile(&j10);
    k9.addAdjacentTile(&k8);
    k9.addAdjacentTile(&l10);
    k10.addAdjacentTile(&k9);
    k10.addAdjacentTile(&j9);
    k10.addAdjacentTile(&l9);
    k10.addAdjacentTile(&j10);
    k10.addAdjacentTile(&l10);
    k11.addAdjacentTile(&j11);
    k11.addAdjacentTile(&l11);
    k11.addAdjacentTile(&j12);
    k11.addAdjacentTile(&l12);
    k11.addAdjacentTile(&k12);
    k12.addAdjacentTile(&j11);
    k12.addAdjacentTile(&l11);
    k12.addAdjacentTile(&j12);
    k12.addAdjacentTile(&l12);
    k12.addAdjacentTile(&j13);
    k12.addAdjacentTile(&k11);
    k13.addAdjacentTile(&j12);
    k13.addAdjacentTile(&k14);
    k13.addAdjacentTile(&j13);
    k13.addAdjacentTile(&j14);
    k13.addAdjacentTile(&l14);
    k14.addAdjacentTile(&l15);
    k14.addAdjacentTile(&k13);
    k14.addAdjacentTile(&j13);
    k14.addAdjacentTile(&k15);
    k14.addAdjacentTile(&l13);
    k14.addAdjacentTile(&j14);
    k14.addAdjacentTile(&l14);
    k14.addAdjacentTile(&j15);
    k15.addAdjacentTile(&j16);
    k15.addAdjacentTile(&k14);
    k15.addAdjacentTile(&j14);
    k15.addAdjacentTile(&k16);
    k15.addAdjacentTile(&l14);
    k15.addAdjacentTile(&j15);
    k16.addAdjacentTile(&k15);
    k16.addAdjacentTile(&j16);
    k16.addAdjacentTile(&j15);
    l1.addAdjacentTile(&l2);
    l1.addAdjacentTile(&k1);
    l1.addAdjacentTile(&m1);
    l1.addAdjacentTile(&k2);
    l1.addAdjacentTile(&m2);
    l2.addAdjacentTile(&l1);
    l2.addAdjacentTile(&k1);
    l2.addAdjacentTile(&m1);
    l2.addAdjacentTile(&k2);
    l2.addAdjacentTile(&m2);
    l2.addAdjacentTile(&m3);
    l3.addAdjacentTile(&k4);
    l3.addAdjacentTile(&k3);
    l3.addAdjacentTile(&l4);
    l4.addAdjacentTile(&k4);
    l4.addAdjacentTile(&k3);
    l4.addAdjacentTile(&l3);
    l5.addAdjacentTile(&l6);
    l5.addAdjacentTile(&k5);
    l5.addAdjacentTile(&m5);
    l5.addAdjacentTile(&k6);
    l5.addAdjacentTile(&m6);
    l6.addAdjacentTile(&k5);
    l6.addAdjacentTile(&m5);
    l6.addAdjacentTile(&k6);
    l6.addAdjacentTile(&m6);
    l6.addAdjacentTile(&m7);
    l6.addAdjacentTile(&l5);
    l7.addAdjacentTile(&m8);
    l7.addAdjacentTile(&l8);
    l7.addAdjacentTile(&m6);
    l7.addAdjacentTile(&k7);
    l7.addAdjacentTile(&m7);
    l7.addAdjacentTile(&k8);
    l8.addAdjacentTile(&m8);
    l8.addAdjacentTile(&k9);
    l8.addAdjacentTile(&m9);
    l8.addAdjacentTile(&l7);
    l8.addAdjacentTile(&k7);
    l8.addAdjacentTile(&l9);
    l8.addAdjacentTile(&m7);
    l8.addAdjacentTile(&k8);
    l9.addAdjacentTile(&m8);
    l9.addAdjacentTile(&k9);
    l9.addAdjacentTile(&m9);
    l9.addAdjacentTile(&k10);
    l9.addAdjacentTile(&m10);
    l9.addAdjacentTile(&l8);
    l9.addAdjacentTile(&k8);
    l9.addAdjacentTile(&l10);
    l10.addAdjacentTile(&k9);
    l10.addAdjacentTile(&m9);
    l10.addAdjacentTile(&m10);
    l10.addAdjacentTile(&k10);
    l10.addAdjacentTile(&m11);
    l10.addAdjacentTile(&l9);
    l11.addAdjacentTile(&m12);
    l11.addAdjacentTile(&l12);
    l11.addAdjacentTile(&m10);
    l11.addAdjacentTile(&k11);
    l11.addAdjacentTile(&m11);
    l11.addAdjacentTile(&k12);
    l12.addAdjacentTile(&l11);
    l12.addAdjacentTile(&k11);
    l12.addAdjacentTile(&m11);
    l12.addAdjacentTile(&k12);
    l12.addAdjacentTile(&m12);
    l13.addAdjacentTile(&m13);
    l13.addAdjacentTile(&k14);
    l13.addAdjacentTile(&l14);
    l13.addAdjacentTile(&m14);
    l14.addAdjacentTile(&l15);
    l14.addAdjacentTile(&k13);
    l14.addAdjacentTile(&m13);
    l14.addAdjacentTile(&k14);
    l14.addAdjacentTile(&m14);
    l14.addAdjacentTile(&k15);
    l14.addAdjacentTile(&l13);
    l14.addAdjacentTile(&m15);
    l15.addAdjacentTile(&l16);
    l15.addAdjacentTile(&k14);
    l15.addAdjacentTile(&m14);
    l15.addAdjacentTile(&m15);
    l15.addAdjacentTile(&l14);
    l15.addAdjacentTile(&m16);
    l16.addAdjacentTile(&l15);
    l16.addAdjacentTile(&m16);
    l16.addAdjacentTile(&m15);
    m1.addAdjacentTile(&l1);
    m1.addAdjacentTile(&n1);
    m1.addAdjacentTile(&l2);
    m1.addAdjacentTile(&n2);
    m1.addAdjacentTile(&m2);
    m2.addAdjacentTile(&l1);
    m2.addAdjacentTile(&n1);
    m2.addAdjacentTile(&l2);
    m2.addAdjacentTile(&n2);
    m2.addAdjacentTile(&m1);
    m2.addAdjacentTile(&n3);
    m2.addAdjacentTile(&m3);
    m3.addAdjacentTile(&m4);
    m3.addAdjacentTile(&l2);
    m3.addAdjacentTile(&n2);
    m3.addAdjacentTile(&n3);
    m3.addAdjacentTile(&m2);
    m3.addAdjacentTile(&n4);
    m4.addAdjacentTile(&n4);
    m4.addAdjacentTile(&n3);
    m4.addAdjacentTile(&m3);
    m5.addAdjacentTile(&n5);
    m5.addAdjacentTile(&l6);
    m5.addAdjacentTile(&n6);
    m5.addAdjacentTile(&m6);
    m5.addAdjacentTile(&l5);
    m6.addAdjacentTile(&n5);
    m6.addAdjacentTile(&l6);
    m6.addAdjacentTile(&n6);
    m6.addAdjacentTile(&l7);
    m6.addAdjacentTile(&m5);
    m6.addAdjacentTile(&n7);
    m6.addAdjacentTile(&m7);
    m6.addAdjacentTile(&l5);
    m7.addAdjacentTile(&m8);
    m7.addAdjacentTile(&l6);
    m7.addAdjacentTile(&n6);
    m7.addAdjacentTile(&l7);
    m7.addAdjacentTile(&n7);
    m7.addAdjacentTile(&l8);
    m7.addAdjacentTile(&m6);
    m7.addAdjacentTile(&n8);
    m8.addAdjacentTile(&l7);
    m8.addAdjacentTile(&n7);
    m8.addAdjacentTile(&l8);
    m8.addAdjacentTile(&n8);
    m8.addAdjacentTile(&l9);
    m8.addAdjacentTile(&m7);
    m9.addAdjacentTile(&n10);
    m9.addAdjacentTile(&m10);
    m9.addAdjacentTile(&l8);
    m9.addAdjacentTile(&l9);
    m9.addAdjacentTile(&n9);
    m9.addAdjacentTile(&l10);
    m10.addAdjacentTile(&n10);
    m10.addAdjacentTile(&l11);
    m10.addAdjacentTile(&m9);
    m10.addAdjacentTile(&n11);
    m10.addAdjacentTile(&m11);
    m10.addAdjacentTile(&l9);
    m10.addAdjacentTile(&n9);
    m10.addAdjacentTile(&l10);
    m11.addAdjacentTile(&n10);
    m11.addAdjacentTile(&l11);
    m11.addAdjacentTile(&n11);
    m11.addAdjacentTile(&l12);
    m11.addAdjacentTile(&m10);
    m11.addAdjacentTile(&n12);
    m11.addAdjacentTile(&m12);
    m11.addAdjacentTile(&l10);
    m12.addAdjacentTile(&n11);
    m12.addAdjacentTile(&l12);
    m12.addAdjacentTile(&l11);
    m12.addAdjacentTile(&m11);
    m13.addAdjacentTile(&m14);
    m13.addAdjacentTile(&l13);
    m13.addAdjacentTile(&n13);
    m13.addAdjacentTile(&l14);
    m13.addAdjacentTile(&n14);
    m14.addAdjacentTile(&l15);
    m14.addAdjacentTile(&n15);
    m14.addAdjacentTile(&m13);
    m14.addAdjacentTile(&l13);
    m14.addAdjacentTile(&m15);
    m14.addAdjacentTile(&n13);
    m14.addAdjacentTile(&l14);
    m14.addAdjacentTile(&n14);
    m15.addAdjacentTile(&l15);
    m15.addAdjacentTile(&n15);
    m15.addAdjacentTile(&l16);
    m15.addAdjacentTile(&n16);
    m15.addAdjacentTile(&m14);
    m15.addAdjacentTile(&l14);
    m15.addAdjacentTile(&m16);
    m15.addAdjacentTile(&n14);
    m16.addAdjacentTile(&l15);
    m16.addAdjacentTile(&n15);
    m16.addAdjacentTile(&l16);
    m16.addAdjacentTile(&n16);
    m16.addAdjacentTile(&m15);
    n1.addAdjacentTile(&n2);
    n1.addAdjacentTile(&m1);
    n1.addAdjacentTile(&o1);
    n1.addAdjacentTile(&m2);
    n1.addAdjacentTile(&o2);
    n2.addAdjacentTile(&o3);
    n2.addAdjacentTile(&n1);
    n2.addAdjacentTile(&m1);
    n2.addAdjacentTile(&n3);
    n2.addAdjacentTile(&o1);
    n2.addAdjacentTile(&m2);
    n2.addAdjacentTile(&o2);
    n2.addAdjacentTile(&m3);
    n3.addAdjacentTile(&o3);
    n3.addAdjacentTile(&m4);
    n3.addAdjacentTile(&o4);
    n3.addAdjacentTile(&n2);
    n3.addAdjacentTile(&m2);
    n3.addAdjacentTile(&n4);
    n3.addAdjacentTile(&o2);
    n3.addAdjacentTile(&m3);
    n4.addAdjacentTile(&o3);
    n4.addAdjacentTile(&m4);
    n4.addAdjacentTile(&o4);
    n4.addAdjacentTile(&o5);
    n4.addAdjacentTile(&n3);
    n4.addAdjacentTile(&m3);
    n5.addAdjacentTile(&m6);
    n5.addAdjacentTile(&m5);
    n5.addAdjacentTile(&n6);
    n6.addAdjacentTile(&n5);
    n6.addAdjacentTile(&m5);
    n6.addAdjacentTile(&n7);
    n6.addAdjacentTile(&m6);
    n6.addAdjacentTile(&m7);
    n6.addAdjacentTile(&o7);
    n7.addAdjacentTile(&m8);
    n7.addAdjacentTile(&o8);
    n7.addAdjacentTile(&n6);
    n7.addAdjacentTile(&m6);
    n7.addAdjacentTile(&n8);
    n7.addAdjacentTile(&m7);
    n7.addAdjacentTile(&o7);
    n8.addAdjacentTile(&m8);
    n8.addAdjacentTile(&o8);
    n8.addAdjacentTile(&n7);
    n8.addAdjacentTile(&m7);
    n8.addAdjacentTile(&o7);
    n9.addAdjacentTile(&n10);
    n9.addAdjacentTile(&m9);
    n9.addAdjacentTile(&o9);
    n9.addAdjacentTile(&m10);
    n9.addAdjacentTile(&o10);
    n10.addAdjacentTile(&m9);
    n10.addAdjacentTile(&n11);
    n10.addAdjacentTile(&o9);
    n10.addAdjacentTile(&m10);
    n10.addAdjacentTile(&o10);
    n10.addAdjacentTile(&m11);
    n10.addAdjacentTile(&n9);
    n11.addAdjacentTile(&n10);
    n11.addAdjacentTile(&m10);
    n11.addAdjacentTile(&n12);
    n11.addAdjacentTile(&o10);
    n11.addAdjacentTile(&m11);
    n11.addAdjacentTile(&m12);
    n12.addAdjacentTile(&n11);
    n12.addAdjacentTile(&m11);
    n13.addAdjacentTile(&o12);
    n13.addAdjacentTile(&m13);
    n13.addAdjacentTile(&o13);
    n13.addAdjacentTile(&m14);
    n13.addAdjacentTile(&o14);
    n13.addAdjacentTile(&n14);
    n14.addAdjacentTile(&n15);
    n14.addAdjacentTile(&m13);
    n14.addAdjacentTile(&o13);
    n14.addAdjacentTile(&o14);
    n14.addAdjacentTile(&m14);
    n14.addAdjacentTile(&m15);
    n14.addAdjacentTile(&o15);
    n14.addAdjacentTile(&n13);
    n15.addAdjacentTile(&n16);
    n15.addAdjacentTile(&m14);
    n15.addAdjacentTile(&o14);
    n15.addAdjacentTile(&o16);
    n15.addAdjacentTile(&o15);
    n15.addAdjacentTile(&m15);
    n15.addAdjacentTile(&m16);
    n15.addAdjacentTile(&n14);
    n16.addAdjacentTile(&n15);
    n16.addAdjacentTile(&m16);
    n16.addAdjacentTile(&o15);
    n16.addAdjacentTile(&m15);
    n16.addAdjacentTile(&o16);
    o1.addAdjacentTile(&n1);
    o1.addAdjacentTile(&p1);
    o1.addAdjacentTile(&n2);
    o1.addAdjacentTile(&p2);
    o1.addAdjacentTile(&o2);
    o2.addAdjacentTile(&o3);
    o2.addAdjacentTile(&n1);
    o2.addAdjacentTile(&p1);
    o2.addAdjacentTile(&n2);
    o2.addAdjacentTile(&p2);
    o2.addAdjacentTile(&n3);
    o2.addAdjacentTile(&o1);
    o2.addAdjacentTile(&p3);
    o3.addAdjacentTile(&o4);
    o3.addAdjacentTile(&n2);
    o3.addAdjacentTile(&p2);
    o3.addAdjacentTile(&n3);
    o3.addAdjacentTile(&p3);
    o3.addAdjacentTile(&n4);
    o3.addAdjacentTile(&o2);
    o3.addAdjacentTile(&p4);
    o4.addAdjacentTile(&o3);
    o4.addAdjacentTile(&p5);
    o4.addAdjacentTile(&o5);
    o4.addAdjacentTile(&n3);
    o4.addAdjacentTile(&p3);
    o4.addAdjacentTile(&n4);
    o4.addAdjacentTile(&p4);
    o5.addAdjacentTile(&p5);
    o5.addAdjacentTile(&o4);
    o5.addAdjacentTile(&p6);
    o5.addAdjacentTile(&o6);
    o5.addAdjacentTile(&n4);
    o5.addAdjacentTile(&p4);
    o6.addAdjacentTile(&o5);
    o6.addAdjacentTile(&p7);
    o6.addAdjacentTile(&p6);
    o6.addAdjacentTile(&p5);
    o7.addAdjacentTile(&o8);
    o7.addAdjacentTile(&n6);
    o7.addAdjacentTile(&p6);
    o7.addAdjacentTile(&n7);
    o7.addAdjacentTile(&p7);
    o7.addAdjacentTile(&n8);
    o7.addAdjacentTile(&p8);
    o8.addAdjacentTile(&n7);
    o8.addAdjacentTile(&p7);
    o8.addAdjacentTile(&n8);
    o8.addAdjacentTile(&p8);
    o8.addAdjacentTile(&o7);
    o9.addAdjacentTile(&p9);
    o9.addAdjacentTile(&n10);
    o9.addAdjacentTile(&p10);
    o9.addAdjacentTile(&o10);
    o9.addAdjacentTile(&n9);
    o10.addAdjacentTile(&p9);
    o10.addAdjacentTile(&n10);
    o10.addAdjacentTile(&p10);
    o10.addAdjacentTile(&n11);
    o10.addAdjacentTile(&o9);
    o10.addAdjacentTile(&p11);
    o10.addAdjacentTile(&n9);
    o11.addAdjacentTile(&o12);
    o11.addAdjacentTile(&p12);
    o11.addAdjacentTile(&p11);
    o11.addAdjacentTile(&p10);
    o12.addAdjacentTile(&o13);
    o12.addAdjacentTile(&p11);
    o12.addAdjacentTile(&p12);
    o12.addAdjacentTile(&n13);
    o12.addAdjacentTile(&o11);
    o12.addAdjacentTile(&p13);
    o13.addAdjacentTile(&o12);
    o13.addAdjacentTile(&p14);
    o13.addAdjacentTile(&o14);
    o13.addAdjacentTile(&p12);
    o13.addAdjacentTile(&n13);
    o13.addAdjacentTile(&p13);
    o13.addAdjacentTile(&n14);
    o14.addAdjacentTile(&p14);
    o14.addAdjacentTile(&n15);
    o14.addAdjacentTile(&o13);
    o14.addAdjacentTile(&p15);
    o14.addAdjacentTile(&o15);
    o14.addAdjacentTile(&n13);
    o14.addAdjacentTile(&p13);
    o14.addAdjacentTile(&n14);
    o15.addAdjacentTile(&p14);
    o15.addAdjacentTile(&n15);
    o15.addAdjacentTile(&p15);
    o15.addAdjacentTile(&n16);
    o15.addAdjacentTile(&o14);
    o15.addAdjacentTile(&p16);
    o15.addAdjacentTile(&o16);
    o15.addAdjacentTile(&n14);
    o16.addAdjacentTile(&n15);
    o16.addAdjacentTile(&p15);
    o16.addAdjacentTile(&n16);
    o16.addAdjacentTile(&p16);
    o16.addAdjacentTile(&o15);
    p1.addAdjacentTile(&o2);
    p1.addAdjacentTile(&o1);
    p1.addAdjacentTile(&p2);
    p2.addAdjacentTile(&o3);
    p2.addAdjacentTile(&p1);
    p2.addAdjacentTile(&o1);
    p2.addAdjacentTile(&p3);
    p2.addAdjacentTile(&o2);
    p3.addAdjacentTile(&o3);
    p3.addAdjacentTile(&o4);
    p3.addAdjacentTile(&p2);
    p3.addAdjacentTile(&o2);
    p3.addAdjacentTile(&p4);
    p4.addAdjacentTile(&o3);
    p4.addAdjacentTile(&p5);
    p4.addAdjacentTile(&o4);
    p4.addAdjacentTile(&o5);
    p4.addAdjacentTile(&p3);
    p5.addAdjacentTile(&o4);
    p5.addAdjacentTile(&p6);
    p5.addAdjacentTile(&o5);
    p5.addAdjacentTile(&o6);
    p5.addAdjacentTile(&p4);
    p6.addAdjacentTile(&p5);
    p6.addAdjacentTile(&o5);
    p6.addAdjacentTile(&p7);
    p6.addAdjacentTile(&o6);
    p6.addAdjacentTile(&o7);
    p7.addAdjacentTile(&o8);
    p7.addAdjacentTile(&p6);
    p7.addAdjacentTile(&o6);
    p7.addAdjacentTile(&p8);
    p7.addAdjacentTile(&o7);
    p8.addAdjacentTile(&p7);
    p8.addAdjacentTile(&o8);
    p8.addAdjacentTile(&o7);
    p9.addAdjacentTile(&o10);
    p9.addAdjacentTile(&o9);
    p9.addAdjacentTile(&p10);
    p10.addAdjacentTile(&p9);
    p10.addAdjacentTile(&o9);
    p10.addAdjacentTile(&p11);
    p10.addAdjacentTile(&o10);
    p10.addAdjacentTile(&o11);
    p11.addAdjacentTile(&o12);
    p11.addAdjacentTile(&p10);
    p11.addAdjacentTile(&o10);
    p11.addAdjacentTile(&p12);
    p11.addAdjacentTile(&o11);
    p12.addAdjacentTile(&o12);
    p12.addAdjacentTile(&o13);
    p12.addAdjacentTile(&p11);
    p12.addAdjacentTile(&o11);
    p12.addAdjacentTile(&p13);
    p13.addAdjacentTile(&o12);
    p13.addAdjacentTile(&p14);
    p13.addAdjacentTile(&o13);
    p13.addAdjacentTile(&o14);
    p13.addAdjacentTile(&p12);
    p14.addAdjacentTile(&o13);
    p14.addAdjacentTile(&p15);
    p14.addAdjacentTile(&o14);
    p14.addAdjacentTile(&o15);
    p14.addAdjacentTile(&p13);
    p15.addAdjacentTile(&p14);
    p15.addAdjacentTile(&o14);
    p15.addAdjacentTile(&p16);
    p15.addAdjacentTile(&o15);
    p15.addAdjacentTile(&o16);
    p16.addAdjacentTile(&p15);
    p16.addAdjacentTile(&o16);
    p16.addAdjacentTile(&o15);
}